[theme]
primaryColor = "#1e88e5"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f7fa"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
